services:
  traefik:
    image: traefik:v3.6
    hostname: proxy
    container_name: mbyte_proxy
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mbyte:
        ipv4_address: 172.25.0.2

  consul:
    image: hashicorp/consul:1.19
    hostname: registry
    container_name: mbyte_registry
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0 -log-level=info
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mbyte"
      - "traefik.http.routers.consul.rule=Host(`registry.mbyte.fr`)"
      - "traefik.http.routers.consul.entrypoints=http"
      - "traefik.http.routers.consul.service=consul-http"
      - "traefik.http.services.consul-http.loadbalancer.server.port=8500"
    depends_on:
      - traefik
    networks:
      mbyte:
        ipv4_address: 172.25.0.10

  db:
    image: postgres
    hostname: db
    container_name: mbyte_db
    environment:
      - POSTGRES_USER=mbyte
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mbyte
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./provisioning/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      mbyte:
        ipv4_address: 172.25.0.11

  keycloak:
    build:
      context: ./auth
      dockerfile: Dockerfile
    hostname: auth
    container_name: mbyte_auth
    command: start --optimized --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://db/keycloak
      KC_DB_USERNAME: mbyte
      KC_DB_PASSWORD: password
      KC_HOSTNAME: auth.mbyte.fr
      KC_HTTP_PORT: 80
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mbyte"
      - "traefik.http.routers.keycloak.rule=Host(`auth.mbyte.fr`)"
      - "traefik.http.routers.keycloak.entrypoints=http"
      - "traefik.http.routers.keycloak.service=keycloak-http"
      - "traefik.http.services.keycloak-http.loadbalancer.server.port=80"
    restart: always
    depends_on:
      - db
      - traefik
    networks:
      mbyte:
        ipv4_address: 172.25.0.12
        aliases:
          - auth.mbyte.fr

  manager:
    image: jerome/manager:25.1-SNAPSHOT
    hostname: manager
    container_name: mbyte_manager
    depends_on:
      - db
      - traefik
      - keycloak
    networks:
      mbyte:
        ipv4_address: 172.25.0.13
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mbyte"
      - "traefik.http.routers.manager.rule=Host(`www.mbyte.fr`)"
      - "traefik.http.routers.manager.entrypoints=http"
      - "traefik.http.routers.manager.service=manager-http"
      - "traefik.http.services.manager-http.loadbalancer.server.port=8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_OIDC_AUTH_SERVER_URL=http://auth.mbyte.fr/realms/mbyte
      - MANAGER.TOPOLOGY.HOST=consul
      - MANAGER.TOPOLOGY.PORT=8500

  store:
    image: jerome/store:25.1-SNAPSHOT
    hostname: sheldon
    container_name: mbyte_store_sheldon
    depends_on:
      - db
      - traefik
      - keycloak
    networks:
      mbyte:
        ipv4_address: 172.25.0.14
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mbyte"
      - "traefik.http.routers.sheldon.rule=Host(`sheldon.s.mbyte.fr`)"
      - "traefik.http.routers.sheldon.entrypoints=http"
      - "traefik.http.routers.sheldon.service=sheldon-http"
      - "traefik.http.services.sheldon-http.loadbalancer.server.port=8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_OIDC_AUTH_SERVER_URL=http://auth.mbyte.fr/realms/mbyte
      - MANAGER.TOPOLOGY.HOST=consul
      - MANAGER.TOPOLOGY.PORT=8500

networks:
  mbyte:
    name: mbyte_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/local/mbyte/db
