services:
  traefik:
    image: traefik:v3.6
    hostname: proxy
    container_name: mbyte.proxy
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./provisioning/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./provisioning/dynamic:/etc/traefik/dynamic:ro
      - ./provisioning/certs:/certs:ro
    networks:
      mbyte.fr:
        ipv4_address: 172.25.0.2

  consul:
    image: hashicorp/consul:1.19
    hostname: registry
    container_name: mbyte.registry
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0 -log-level=info
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mbyte.fr"
      - "traefik.http.routers.consul.rule=Host(`registry.mbyte.fr`)"
      - "traefik.http.routers.consul.entrypoints=websecure"
      - "traefik.http.routers.consul.tls=true"
      - "traefik.http.routers.consul-http.rule=Host(`registry.mbyte.fr`)"
      - "traefik.http.routers.consul-http.entrypoints=web"
      - "traefik.http.routers.consul-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
    depends_on:
      - traefik
    networks:
      mbyte.fr:
        ipv4_address: 172.25.0.3

  db:
    image: postgres:latest
    hostname: db
    container_name: mbyte.db
    environment:
      - POSTGRES_USER=mbyte
      - POSTGRES_PASSWORD=password
    volumes:
      - mbyte.db.volume:/var/lib/postgresql
      - ./provisioning/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      mbyte.fr:
        ipv4_address: 172.25.0.4

  keycloak:
    build:
      context: .
      dockerfile: auth/Dockerfile
    hostname: auth
    container_name: mbyte.auth
    command: start --optimized --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://db/keycloak
      KC_DB_USERNAME: mbyte
      KC_DB_PASSWORD: password
      KC_HOSTNAME: auth.mbyte.fr
      KC_HOSTNAME_PROTOCOL: https
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 80
      KC_PROXY_HEADERS: xforwarded
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mbyte.fr"
      - "traefik.http.routers.keycloak.rule=Host(`auth.mbyte.fr`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak-http.rule=Host(`auth.mbyte.fr`)"
      - "traefik.http.routers.keycloak-http.entrypoints=web"
      - "traefik.http.routers.keycloak-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Host=auth.mbyte.fr"
      - "traefik.http.routers.keycloak.middlewares=keycloak-headers"
      - "traefik.http.services.keycloak.loadbalancer.server.port=80"
    restart: always
    depends_on:
      - db
      - traefik
    networks:
      mbyte.fr:
        ipv4_address: 172.25.0.5
        aliases:
          - auth.mbyte.fr

  manager:
    image: mbyte/manager:26.2-SNAPSHOT
    build:
      context: .
      dockerfile: manager/src/main/docker/Dockerfile.multistage
    hostname: manager
    container_name: mbyte.manager
    depends_on:
      - db
      - traefik
      - keycloak
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    extra_hosts:
      - "auth.mbyte.fr:172.25.0.2"
    networks:
      mbyte.fr:
        ipv4_address: 172.25.0.6
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mbyte.fr"
      - "traefik.http.routers.manager.rule=Host(`manager.mbyte.fr`)"
      - "traefik.http.routers.manager.entrypoints=websecure"
      - "traefik.http.routers.manager.tls=true"
      - "traefik.http.routers.manager-http.rule=Host(`manager.mbyte.fr`)"
      - "traefik.http.routers.manager-http.entrypoints=web"
      - "traefik.http.routers.manager-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.manager.loadbalancer.server.port=8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_OIDC_AUTH_SERVER_URL=https://auth.mbyte.fr/realms/mbyte
      - MANAGER_TOPOLOGY_HOST=consul
      - MANAGER_TOPOLOGY_PORT=8500
      - MANAGER_INSTANCE=mbyte.fr

  gui:
    image: mbyte/gui:26.2-SNAPSHOT
    build:
      context: gui
      dockerfile: Dockerfile.multistage
    hostname: www
    container_name: mbyte.gui
    depends_on:
      - manager
    networks:
      mbyte.fr:
        ipv4_address: 172.25.0.7
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mbyte.fr"
      - "traefik.http.routers.gui.rule=Host(`www.mbyte.fr`)"
      - "traefik.http.routers.gui.entrypoints=websecure"
      - "traefik.http.routers.gui.tls=true"
      - "traefik.http.routers.gui-http.rule=Host(`www.mbyte.fr`)"
      - "traefik.http.routers.gui-http.entrypoints=web"
      - "traefik.http.routers.gui-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.gui.loadbalancer.server.port=80"

  store-image:
    image: mbyte/store:26.2-SNAPSHOT
    build:
      context: .
      dockerfile: store/src/main/docker/Dockerfile.multistage
    profiles:
      - tools

networks:
  mbyte.fr:
    name: mbyte.fr
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

volumes:
  mbyte.db.volume:
    name: mbyte.fr.db_v2
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db
